services:
  db:
    container_name: flagatron-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: flagatron-app
    build: .
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env

  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
